# Generated by Django 4.2.6 on 2023-12-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_sociallink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
